[tool.briefcase]
project_name = "GJS Calculator"
bundle = "org.lyra"
version = "0.0.1"
url = "https://lyra.org/gjscalculator"
license = "Apache Software License"
author = 'gstein'
author_email = "gstein@gmail.com"

[tool.briefcase.app.gjscalculator]
formal_name = "GJS Calculator"
description = "Simple calculator"
icon = "src/gjscalculator/resources/gjscalculator"
sources = ['src/gjscalculator']
requires = []


[tool.briefcase.app.gjscalculator.macOS]
requires = [
    'toga-cocoa>=0.3.0.dev20',
]

[tool.briefcase.app.gjscalculator.linux]
requires = [
    'toga-gtk>=0.3.0.dev20',
]
system_requires = [
    'libgirepository1.0-dev',
    'libcairo2-dev',
    'libpango1.0-dev',
    'libwebkitgtk-3.0-0',
    'gir1.2-webkit-3.0',
]

[tool.briefcase.app.gjscalculator.windows]
requires = [
    'toga-winforms>=0.3.0.dev20',
]

# Mobile deployments
[tool.briefcase.app.gjscalculator.iOS]
requires = [
    'toga-iOS>=0.3.0.dev20',
]

[tool.briefcase.app.gjscalculator.android]
requires = [
    'toga-android>=0.3.0.dev20',
]
